### ISSUE TITLE
Testing of folders blank // Vocabulary testing not working

### ISSUE THREAD

**Issue by Arushsec** [vtp6/vtp6.github.io#4]
Hello Mr. Nayak,
Issues have recently been encountered as of 20/10/2024 by me and my peers when clicking the "Start" Button in the "Folders" section of the website. Upon the button being clicked, instead of the usual text prompt and vocabulary testing, the page goes blank. To further demonstrate this issue, attached is a screen recorded video file by one of my companions.https://github.com/user-attachments/assets/1aa6ef45-eff4-4102-b255-6066cba30833
Thank you for all of your excellent and high-calibre work on vtp6 and CS.RN. It is supremely appreciated by my fellow students. And that chemical equation balancer too it helped immensely. Also I saw your addition of custom files that looks absolutely spectacular. And the rest of your github, you have a A- which is great!!
Well wishes,
Arushsec

**Comment by nayakrujul** [comment]
Thank you for your bug report! The bug was introduced yesterday when I was working on custom sets, but it has now been fixed by [this commit](https://github.com/vtp6/vtp6.github.io/commit/b4838d674b14283fc019153b4ea4180b4d7e81f3).

(It might take some time to deploy, but if you try again in an hour or so it should be working by then)
